-- CSDL: Quản lý cửa hàng dụng cụ bóng rổ (SQL Server)
CREATE DATABASE QLBongRo;
GO
USE QLBongRo;
GO
CREATE TABLE LoaiSP   (MaLoai INT IDENTITY PRIMARY KEY, TenLoai NVARCHAR(100) NOT NULL);
CREATE TABLE NhaCungCap(MaNCC INT IDENTITY PRIMARY KEY, TenNCC NVARCHAR(150) NOT NULL, SDT VARCHAR(15), DiaChi NVARCHAR(200));
CREATE TABLE SanPham (
  MaSP INT IDENTITY PRIMARY KEY, TenSP NVARCHAR(150) NOT NULL,
  MaLoai INT REFERENCES LoaiSP(MaLoai), MaNCC INT REFERENCES NhaCungCap(MaNCC),
  Hang NVARCHAR(50), Size NVARCHAR(20), GiaNhap MONEY NOT NULL, GiaBan MONEY NOT NULL,
  SoLuongTon INT NOT NULL DEFAULT 0 CHECK (SoLuongTon >= 0));
CREATE TABLE KhachHang(MaKH INT IDENTITY PRIMARY KEY, HoTen NVARCHAR(100) NOT NULL, SDT VARCHAR(15), DiemTichLuy INT DEFAULT 0);
CREATE TABLE NhanVien (MaNV INT IDENTITY PRIMARY KEY, HoTen NVARCHAR(100) NOT NULL, TenDangNhap VARCHAR(50) UNIQUE, MatKhauHash VARCHAR(100), VaiTro NVARCHAR(20));
CREATE TABLE HoaDon (
  MaHD INT IDENTITY PRIMARY KEY, NgayLap DATETIME DEFAULT GETDATE(),
  MaNV INT REFERENCES NhanVien(MaNV), MaKH INT REFERENCES KhachHang(MaKH), TongTien MONEY DEFAULT 0);
CREATE TABLE ChiTietHoaDon (
  MaHD INT REFERENCES HoaDon(MaHD), MaSP INT REFERENCES SanPham(MaSP),
  SoLuong INT NOT NULL CHECK (SoLuong > 0), DonGia MONEY NOT NULL, PRIMARY KEY (MaHD, MaSP));
CREATE TABLE PhieuNhap (MaPN INT IDENTITY PRIMARY KEY, NgayNhap DATETIME DEFAULT GETDATE(), MaNCC INT REFERENCES NhaCungCap(MaNCC), MaNV INT REFERENCES NhanVien(MaNV));
CREATE TABLE ChiTietPhieuNhap (
  MaPN INT REFERENCES PhieuNhap(MaPN), MaSP INT REFERENCES SanPham(MaSP),
  SoLuong INT NOT NULL CHECK (SoLuong > 0), GiaNhap MONEY NOT NULL, PRIMARY KEY (MaPN, MaSP));
GO
-- Trừ tồn kho tự động khi bán hàng
CREATE TRIGGER trg_BanHang ON ChiTietHoaDon AFTER INSERT AS
  UPDATE s SET s.SoLuongTon = s.SoLuongTon - i.SoLuong
  FROM SanPham s JOIN inserted i ON s.MaSP = i.MaSP;
